### ISSUE TITLE
Weather data

### ISSUE THREAD

**Issue by LeeDoYup** [snehasinghania/STResNet#3]
I can not find the weather data and corresponding source codes.
However, the weather data is contained in the original paper.

**Comment by alexofficial** [comment]
> 
> 
> I can not find the weather data and corresponding source codes.
> However, the weather data is contained in the original paper.

I agree with @LeeDoYup, this implementation seems to have only the fusion part. Is this implementation in progress or it does not include the external feature extraction? Furthermore, how can be sure if this implementation reflects 100% to the original paper?
